export const PERMISSIONS = {
  MANAGE_COMPANIES: "manage_companies",
  VIEW_GLOBAL_REPORTS: "view_global_reports",
  DOWNLOAD_GLOBAL_DATA: "download_global_data",
  MANAGE_GLOBAL_USERS: "manage_global_users",

  MANAGE_SCHOOLS: "manage_schools",
  MANAGE_SCHOOL_USERS: "manage_school_users",
  MANAGE_EMPLOYEES: "manage_employees",
  MANAGE_COMPETENCIES: "manage_competencies",
  MANAGE_METRICS: "manage_metrics",
  MANAGE_EVALUATION_CYCLES: "manage_evaluation_cycles",
  MANAGE_EVALUATIONS: "manage_evaluations",
  MANAGE_DEVELOPMENT_PLANS: "manage_development_plans",
  MANAGE_SETTINGS: "manage_settings",

  VIEW_REPORTS: "view_reports",
  DOWNLOAD_REPORTS: "download_reports",
  DOWNLOAD_TEAM_REPORTS: "download_team_reports",
  DOWNLOAD_SELF_REPORT: "download_self_report",

  EVALUATE_TEAM: "evaluate_team",
  SELF_EVALUATE: "self_evaluate",
  VIEW_SELF_PROFILE: "view_self_profile",
  VIEW_TEAM: "view_team",

  READ_ONLY_ACCESS: "read_only_access",
  VIEW_AUDIT: "view_audit",
};

export const PERMISSION_SEED = [
  { code: PERMISSIONS.MANAGE_COMPANIES, label: "Gestionar colegios/empresas", module: "companies" },
  { code: PERMISSIONS.VIEW_GLOBAL_REPORTS, label: "Ver reportes globales", module: "reports" },
  { code: PERMISSIONS.DOWNLOAD_GLOBAL_DATA, label: "Descargar base global", module: "exports" },
  { code: PERMISSIONS.MANAGE_GLOBAL_USERS, label: "Gestionar usuarios globales", module: "users" },
  { code: PERMISSIONS.MANAGE_SCHOOLS, label: "Gestionar sedes/colegios", module: "schools" },
  { code: PERMISSIONS.MANAGE_SCHOOL_USERS, label: "Gestionar usuarios del colegio", module: "users" },
  { code: PERMISSIONS.MANAGE_EMPLOYEES, label: "Gestionar empleados", module: "employees" },
  { code: PERMISSIONS.MANAGE_COMPETENCIES, label: "Gestionar competencias", module: "competencies" },
  { code: PERMISSIONS.MANAGE_METRICS, label: "Gestionar metricas", module: "metrics" },
  { code: PERMISSIONS.MANAGE_EVALUATION_CYCLES, label: "Gestionar ciclos", module: "evaluation-cycles" },
  { code: PERMISSIONS.MANAGE_EVALUATIONS, label: "Gestionar evaluaciones", module: "evaluations" },
  { code: PERMISSIONS.MANAGE_DEVELOPMENT_PLANS, label: "Gestionar planes de desarrollo", module: "development-plans" },
  { code: PERMISSIONS.MANAGE_SETTINGS, label: "Gestionar configuracion", module: "settings" },
  { code: PERMISSIONS.VIEW_REPORTS, label: "Ver reportes", module: "reports" },
  { code: PERMISSIONS.DOWNLOAD_REPORTS, label: "Descargar reportes", module: "exports" },
  { code: PERMISSIONS.DOWNLOAD_TEAM_REPORTS, label: "Descargar reportes del equipo", module: "exports" },
  { code: PERMISSIONS.DOWNLOAD_SELF_REPORT, label: "Descargar reporte propio", module: "exports" },
  { code: PERMISSIONS.EVALUATE_TEAM, label: "Evaluar equipo", module: "evaluations" },
  { code: PERMISSIONS.SELF_EVALUATE, label: "Realizar autoevaluacion", module: "evaluations" },
  { code: PERMISSIONS.VIEW_SELF_PROFILE, label: "Ver perfil propio", module: "employees" },
  { code: PERMISSIONS.VIEW_TEAM, label: "Ver equipo a cargo", module: "employees" },
  { code: PERMISSIONS.READ_ONLY_ACCESS, label: "Acceso solo lectura", module: "shared" },
  { code: PERMISSIONS.VIEW_AUDIT, label: "Ver auditoria", module: "audit" },
];

export const ROLE_DEFINITIONS = [
  {
    code: "SUPER_ADMIN",
    nombre: "Super Admin",
    scope: "global",
    permisos: [
      PERMISSIONS.MANAGE_COMPANIES,
      PERMISSIONS.VIEW_GLOBAL_REPORTS,
      PERMISSIONS.DOWNLOAD_GLOBAL_DATA,
      PERMISSIONS.MANAGE_GLOBAL_USERS,
      PERMISSIONS.MANAGE_SCHOOLS,
      PERMISSIONS.MANAGE_SCHOOL_USERS,
      PERMISSIONS.MANAGE_EMPLOYEES,
      PERMISSIONS.MANAGE_COMPETENCIES,
      PERMISSIONS.MANAGE_METRICS,
      PERMISSIONS.MANAGE_EVALUATION_CYCLES,
      PERMISSIONS.MANAGE_EVALUATIONS,
      PERMISSIONS.MANAGE_DEVELOPMENT_PLANS,
      PERMISSIONS.MANAGE_SETTINGS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.DOWNLOAD_REPORTS,
      PERMISSIONS.VIEW_AUDIT,
    ],
  },
  {
    code: "ADMIN_COLEGIO",
    nombre: "Director",
    scope: "school",
    permisos: [
      PERMISSIONS.MANAGE_SCHOOLS,
      PERMISSIONS.MANAGE_SCHOOL_USERS,
      PERMISSIONS.MANAGE_EMPLOYEES,
      PERMISSIONS.MANAGE_COMPETENCIES,
      PERMISSIONS.MANAGE_METRICS,
      PERMISSIONS.MANAGE_EVALUATION_CYCLES,
      PERMISSIONS.MANAGE_EVALUATIONS,
      PERMISSIONS.MANAGE_DEVELOPMENT_PLANS,
      PERMISSIONS.MANAGE_SETTINGS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.DOWNLOAD_REPORTS,
      PERMISSIONS.VIEW_AUDIT,
    ],
  },
  {
    code: "RRHH",
    nombre: "RRHH",
    scope: "school",
    permisos: [
      PERMISSIONS.MANAGE_EMPLOYEES,
      PERMISSIONS.MANAGE_EVALUATIONS,
      PERMISSIONS.MANAGE_DEVELOPMENT_PLANS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.DOWNLOAD_REPORTS,
    ],
  },
  {
    code: "JEFE",
    nombre: "Jefe",
    scope: "team",
    permisos: [
      PERMISSIONS.VIEW_TEAM,
      PERMISSIONS.EVALUATE_TEAM,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.DOWNLOAD_TEAM_REPORTS,
    ],
  },
  {
    code: "EMPLEADO",
    nombre: "Empleado",
    scope: "self",
    permisos: [
      PERMISSIONS.VIEW_SELF_PROFILE,
      PERMISSIONS.SELF_EVALUATE,
      PERMISSIONS.DOWNLOAD_SELF_REPORT,
    ],
  },
  {
    code: "LECTOR",
    nombre: "Lector / Auditor",
    scope: "read_only",
    permisos: [PERMISSIONS.READ_ONLY_ACCESS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.VIEW_AUDIT],
  },
];
