export const UI_TRANSLATIONS = {
  es: {
    "nav.home": "Inicio",
    "nav.people": "Personas",
    "nav.peopleGroup": "Personas",
    "nav.orgchart": "Organigrama",
    "nav.users": "Usuarios",
    "nav.access": "Accesos",
    "nav.skills": "Habilidades",
    "nav.performance": "Evaluación de desempeño",
    "nav.evaluations": "Evaluaciones",
    "nav.actionPlans": "Planes de acción",
    "nav.cycles": "Ciclos",
    "nav.metrics": "Mediciones",
    "nav.metricsShort": "Mediciones",
    "nav.calibration": "Calibración",
    "nav.news": "Novedades",
    "nav.migration": "Migración",
    "nav.report": "Reportes",
    "nav.development": "Desarrollo",
    "nav.dataCenter": "Centro de datos",
    "nav.import": "Importación",
    "nav.settings": "Configuración",
    "nav.platform": "Plataforma",
    "nav.organizations": "Organizaciones",
    "topbar.organization": "Organización activa",
    "topbar.searchPlaceholder": "Buscar… (Ctrl+K)",
    "topbar.searchHint": "La búsqueda se aplica a las listas visibles.",
    "topbar.notifications": "Notificaciones",
    "topbar.logout": "Salir",
    "topbar.upToDate": "Al día",
    "common.soon": "Pronto",
    "common.language": "Idioma",
    "common.english": "English (US)",
    "common.spanish": "Español",
    "common.searchApplies": "La búsqueda se aplica a las listas visibles de esta pantalla.",
    "common.retry": "Reintentar",
    "common.close": "Cerrar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.create": "Crear",
    "common.loading": "Cargando...",
    "common.noData": "Sin datos",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.status": "Estado",
    "common.name": "Nombre",
    "common.email": "Email",
    "common.role": "Rol",
    "common.area": "Área",
    "common.date": "Fecha",
    "common.actions": "Acciones",
    "common.records": "Registros",
    "common.results": "Resultados",
    "common.seeMore": "Ver más",
    "common.seeLess": "Ver menos",
    "common.view": "Ver",
    "common.new": "Nuevo",
    "common.total": "Total",
    "common.active_f": "Activas",
    "common.pending": "Pendientes",
    "common.completed": "Completadas",
    "common.inProgress": "En progreso",
    "common.overdue": "Vencido",
    "common.priority": "Prioridad",
    "common.responsible": "Responsable",
    "common.employee": "Colaborador",
    "common.evaluator": "Evaluador",
    "common.period": "Período",
    "common.result": "Resultado",
    "common.objective": "Fecha objetivo",
    "common.progress": "Progreso",
    "dashboard.greeting.morning": "Buenos días",
    "dashboard.greeting.afternoon": "Buenas tardes",
    "dashboard.greeting.evening": "Buenas noches",
    "dashboard.tour": "Recorrido guiado",
    "dashboard.tourSub": "Flujo recomendado para una demo o piloto",
    "skills.title": "Habilidades",
    "skills.subtitle": "Gestioná las habilidades que se evalúan en la organización.",
    "skills.new": "Nueva habilidad",
    "skills.total": "Total",
    "skills.active": "Activas",
    "skills.technical": "Técnicas",
    "skills.soft": "Blandas",
    "skills.colName": "Habilidad",
    "skills.colCategory": "Categoría",
    "skills.colDesc": "Descripción",
    "skills.colLevel": "Nivel",
    "skills.colStatus": "Estado",
    "skills.categoryTechnical": "Técnica",
    "skills.categorySoft": "Blanda",
    "skills.levelBasic": "Básico",
    "skills.levelIntermediate": "Intermedio",
    "skills.levelAdvanced": "Avanzado",
    "skills.scopeGlobal": "Toda la organización",
    "skills.scopeArea": "Área específica",
    "skills.editTitle": "Editar habilidad",
    "skills.newTitle": "Nueva habilidad",
    "eval.title": "Evaluaciones",
    "eval.subtitle": "Gestioná las evaluaciones por ciclo y hacé seguimiento del avance.",
    "eval.myTitle": "Mi evaluación",
    "eval.mySubtitle": "Estas son las habilidades que se están evaluando en tu ciclo actual.",
    "eval.new": "Nueva evaluación",
    "eval.list": "Evaluaciones asignadas",
    "eval.active": "Evaluaciones activas",
    "eval.pending": "Pendientes",
    "eval.completed": "Completadas",
    "eval.average": "Promedio general",
    "eval.skillsEvaluated": "Habilidades evaluadas",
    "eval.currentAvg": "Promedio actual",
    "eval.cycleStart": "Inicio",
    "eval.cycleMid": "Midterm",
    "eval.cycleFinal": "Final",
    "eval.banner": "Las habilidades base son comunes para todas las áreas y empleados. Algunas habilidades adicionales pueden aplicarse a una o más áreas específicas.",
    "eval.status.draft": "Borrador",
    "eval.status.sent": "Enviada",
    "eval.status.reviewed": "Revisada",
    "eval.status.closed": "Cerrada",
    "eval.status.pending": "Pendiente",
    "eval.status.inProgress": "En progreso",
    "eval.type.self": "Autoevaluación",
    "eval.type.manager": "Jefatura",
    "eval.type.final": "Cierre final",
    "exec.title": "Reporte ejecutivo",
    "exec.export": "Exportar PDF",
    "exec.summary": "Resumen ejecutivo",
    "exec.signals": "Indicadores clave",
    "plans.title": "Planes de acción",
    "plans.subtitle": "Definí y hacé seguimiento de las acciones de mejora.",
    "plans.new": "Nuevo plan",
    "plans.list": "Planes de desarrollo",
    "plans.active": "Planes activos",
    "plans.tracking": "En seguimiento",
    "plans.completed": "Completados",
    "plans.dueSoon": "Vencen esta semana",
    "plans.colPlan": "Plan",
    "plans.colEmployee": "Colaborador",
    "plans.colSkill": "Habilidad asociada",
    "plans.colDue": "Fecha objetivo",
    "plans.colProgress": "Progreso",
    "plans.status.pending": "Pendiente",
    "plans.status.active": "En curso",
    "plans.status.tracking": "En seguimiento",
    "plans.status.closed": "Completado",
    "plans.status.overdue": "Vencido",
    "cycles.new": "Nuevo ciclo",
    "cycles.list": "Ciclos cargados",
    "onboarding.title": "Primeros pasos",
    "onboarding.progress": "Progreso de configuración",
  },
  en: {
    "nav.home": "Home",
    "nav.people": "People",
    "nav.peopleGroup": "People",
    "nav.orgchart": "Org Chart",
    "nav.users": "Users",
    "nav.access": "Access",
    "nav.skills": "Skills",
    "nav.performance": "Performance",
    "nav.evaluations": "Evaluations",
    "nav.actionPlans": "Action Plans",
    "nav.cycles": "Cycles",
    "nav.metrics": "Objectives / KPIs",
    "nav.metricsShort": "KPIs",
    "nav.calibration": "Calibration",
    "nav.news": "Updates",
    "nav.migration": "Migration",
    "nav.report": "Reports",
    "nav.development": "Development",
    "nav.dataCenter": "Data center",
    "nav.import": "Import",
    "nav.settings": "Settings",
    "nav.platform": "Platform",
    "nav.organizations": "Organizations",
    "topbar.organization": "Active organization",
    "topbar.searchPlaceholder": "Search… (Ctrl+K)",
    "topbar.searchHint": "Search applies to the visible lists.",
    "topbar.notifications": "Notifications",
    "topbar.logout": "Sign out",
    "topbar.upToDate": "Up to date",
    "common.soon": "Soon",
    "common.language": "Language",
    "common.english": "English (US)",
    "common.spanish": "Español",
    "common.searchApplies": "Search applies to the visible lists in this screen.",
    "common.retry": "Retry",
    "common.close": "Close",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.loading": "Loading...",
    "common.noData": "No data",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.status": "Status",
    "common.name": "Name",
    "common.email": "Email",
    "common.role": "Role",
    "common.area": "Department",
    "common.date": "Date",
    "common.actions": "Actions",
    "common.records": "Records",
    "common.results": "Results",
    "common.seeMore": "See more",
    "common.seeLess": "See less",
    "common.view": "View",
    "common.new": "New",
    "common.total": "Total",
    "common.active_f": "Active",
    "common.pending": "Pending",
    "common.completed": "Completed",
    "common.inProgress": "In progress",
    "common.overdue": "Overdue",
    "common.priority": "Priority",
    "common.responsible": "Responsible",
    "common.employee": "Collaborator",
    "common.evaluator": "Evaluator",
    "common.period": "Period",
    "common.result": "Result",
    "common.objective": "Target date",
    "common.progress": "Progress",
    "dashboard.greeting.morning": "Good morning",
    "dashboard.greeting.afternoon": "Good afternoon",
    "dashboard.greeting.evening": "Good evening",
    "dashboard.tour": "Guided tour",
    "dashboard.tourSub": "Recommended flow for a demo or pilot",
    "skills.title": "Skills",
    "skills.subtitle": "Manage the skills evaluated in your organization.",
    "skills.new": "New skill",
    "skills.total": "Total",
    "skills.active": "Active",
    "skills.technical": "Technical",
    "skills.soft": "Soft",
    "skills.colName": "Skill",
    "skills.colCategory": "Category",
    "skills.colDesc": "Description",
    "skills.colLevel": "Level",
    "skills.colStatus": "Status",
    "skills.categoryTechnical": "Technical",
    "skills.categorySoft": "Soft",
    "skills.levelBasic": "Basic",
    "skills.levelIntermediate": "Intermediate",
    "skills.levelAdvanced": "Advanced",
    "skills.scopeGlobal": "Entire organization",
    "skills.scopeArea": "Specific area",
    "skills.editTitle": "Edit skill",
    "skills.newTitle": "New skill",
    "eval.title": "Evaluations",
    "eval.subtitle": "Manage evaluations by cycle and track progress.",
    "eval.myTitle": "My Evaluation",
    "eval.mySubtitle": "These are the skills being evaluated in your current cycle.",
    "eval.new": "New evaluation",
    "eval.list": "Assigned evaluations",
    "eval.active": "Active evaluations",
    "eval.pending": "Pending",
    "eval.completed": "Completed",
    "eval.average": "Overall average",
    "eval.skillsEvaluated": "Skills evaluated",
    "eval.currentAvg": "Current average",
    "eval.cycleStart": "Start",
    "eval.cycleMid": "Midterm",
    "eval.cycleFinal": "Final",
    "eval.banner": "Base skills are shared across all areas and employees. Some additional skills may apply to specific areas.",
    "eval.status.draft": "Draft",
    "eval.status.sent": "Submitted",
    "eval.status.reviewed": "Reviewed",
    "eval.status.closed": "Closed",
    "eval.status.pending": "Pending",
    "eval.status.inProgress": "In progress",
    "eval.type.self": "Self-evaluation",
    "eval.type.manager": "Manager review",
    "eval.type.final": "Final review",
    "exec.title": "Executive report",
    "exec.export": "Export PDF",
    "exec.summary": "Executive summary",
    "exec.signals": "Key indicators",
    "plans.title": "Action Plans",
    "plans.subtitle": "Define and track improvement actions.",
    "plans.new": "New plan",
    "plans.list": "Development plans",
    "plans.active": "Active plans",
    "plans.tracking": "In tracking",
    "plans.completed": "Completed",
    "plans.dueSoon": "Due this week",
    "plans.colPlan": "Plan",
    "plans.colEmployee": "Collaborator",
    "plans.colSkill": "Associated skill",
    "plans.colDue": "Target date",
    "plans.colProgress": "Progress",
    "plans.status.pending": "Pending",
    "plans.status.active": "In progress",
    "plans.status.tracking": "In tracking",
    "plans.status.closed": "Completed",
    "plans.status.overdue": "Overdue",
    "cycles.new": "New cycle",
    "cycles.list": "Evaluation cycles",
    "onboarding.title": "Getting started",
    "onboarding.progress": "Setup progress",
  },
};

export function resolveUiText(language, key, fallback = "") {
  return UI_TRANSLATIONS[language]?.[key] || fallback || key;
}
