export const UI_TRANSLATIONS = {
  es: {
    "nav.home": "Inicio",
    "nav.people": "Personas",
    "nav.evaluations": "Evaluaciones",
    "nav.cycles": "Ciclos",
    "nav.metrics": "Mediciones",
    "nav.metricsShort": "Mediciones",
    "nav.skills": "Competencias",
    "nav.development": "Desarrollo",
    "nav.report": "Reporte ejecutivo",
    "nav.dataCenter": "Centro de datos",
    "nav.import": "Importación",
    "nav.users": "Usuarios",
    "nav.settings": "Configuración",
    "nav.platform": "Plataforma",
    "nav.organizations": "Organizaciones",
    "nav.news": "Novedades",
    "topbar.organization": "Organización activa",
    "topbar.searchPlaceholder": "Buscar en la pantalla actual...",
    "topbar.searchHint": "La búsqueda se aplica a las listas visibles.",
    "topbar.light": "Modo claro",
    "topbar.dark": "Modo oscuro",
    "topbar.notifications": "Notificaciones",
    "topbar.news": "Novedades",
    "topbar.logout": "Salir",
    "topbar.upToDate": "Al día",
    "common.soon": "Pronto",
    "common.language": "Idioma",
    "common.theme": "Tema",
    "common.english": "English",
    "common.spanish": "Español",
    "common.searchApplies": "La búsqueda se aplica a las listas visibles de esta pantalla.",
    "common.retry": "Reintentar",
    "common.close": "Cerrar",
  },
  en: {
    "nav.home": "Home",
    "nav.people": "People",
    "nav.evaluations": "Evaluations",
    "nav.cycles": "Cycles",
    "nav.metrics": "Objectives / Indicators",
    "nav.metricsShort": "Indicators",
    "nav.skills": "Competencies",
    "nav.development": "Development",
    "nav.report": "Executive report",
    "nav.dataCenter": "Data center",
    "nav.import": "Import",
    "nav.users": "Users",
    "nav.settings": "Settings",
    "nav.platform": "Platform",
    "nav.organizations": "Organizations",
    "nav.news": "Updates",
    "topbar.organization": "Active organization",
    "topbar.searchPlaceholder": "Search within the current screen...",
    "topbar.searchHint": "Search applies to the visible lists.",
    "topbar.light": "Light mode",
    "topbar.dark": "Dark mode",
    "topbar.notifications": "Notifications",
    "topbar.news": "Updates",
    "topbar.logout": "Sign out",
    "topbar.upToDate": "Up to date",
    "common.soon": "Soon",
    "common.language": "Language",
    "common.theme": "Theme",
    "common.english": "English",
    "common.spanish": "Español",
    "common.searchApplies": "Search applies to the visible lists in this screen.",
    "common.retry": "Retry",
    "common.close": "Close",
  },
};

export function resolveUiText(language, key, fallback = "") {
  return UI_TRANSLATIONS[language]?.[key] || fallback || key;
}
