export const UI_TRANSLATIONS = {
  es: {
    "nav.home": "Inicio",
    "nav.people": "Personas",
    "nav.evaluations": "Evaluaciones",
    "nav.cycles": "Ciclos",
    "nav.metrics": "Mediciones",
    "nav.metricsShort": "Mediciones",
    "nav.skills": "Competencias",
    "nav.development": "Desarrollo",
    "nav.report": "Reportes",
    "nav.dataCenter": "Centro de datos",
    "nav.import": "Importación",
    "nav.users": "Usuarios",
    "nav.settings": "Configuración",
    "nav.platform": "Plataforma",
    "nav.organizations": "Organizaciones",
    "nav.news": "Novedades",
    "topbar.organization": "Organización activa",
    "topbar.searchPlaceholder": "Buscar… (Ctrl+K)",
    "topbar.searchHint": "La búsqueda se aplica a las listas visibles.",
    "topbar.notifications": "Notificaciones",
    "topbar.news": "Novedades",
    "topbar.logout": "Salir",
    "topbar.upToDate": "Al día",
    "common.soon": "Pronto",
    "common.language": "Idioma",
    "common.english": "English (US)",
    "common.spanish": "Español",
    "common.searchApplies": "La búsqueda se aplica a las listas visibles de esta pantalla.",
    "common.retry": "Reintentar",
    "common.close": "Cerrar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.create": "Crear",
    "common.loading": "Cargando...",
    "common.noData": "Sin datos",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.status": "Estado",
    "common.name": "Nombre",
    "common.email": "Email",
    "common.role": "Rol",
    "common.area": "Área",
    "common.date": "Fecha",
    "common.actions": "Acciones",
    "common.records": "Registros",
    "common.results": "Resultados",
    "common.seeMore": "Ver más",
    "common.seeLess": "Ver menos",
    "dashboard.greeting.morning": "Buenos días",
    "dashboard.greeting.afternoon": "Buenas tardes",
    "dashboard.greeting.evening": "Buenas noches",
    "dashboard.tour": "Recorrido guiado",
    "dashboard.tourSub": "Flujo recomendado para una demo o piloto",
    "eval.new": "Nueva evaluación",
    "eval.list": "Evaluaciones asignadas",
    "eval.status.draft": "Borrador",
    "eval.status.sent": "Enviada",
    "eval.status.reviewed": "Revisada",
    "eval.status.closed": "Cerrada",
    "eval.type.self": "Autoevaluación",
    "eval.type.manager": "Jefatura",
    "eval.type.final": "Cierre final",
    "exec.title": "Reporte ejecutivo",
    "exec.export": "Exportar PDF",
    "exec.summary": "Resumen ejecutivo",
    "exec.signals": "Indicadores clave",
    "plans.new": "Nuevo plan",
    "plans.list": "Planes de desarrollo",
    "plans.status.pending": "Pendiente",
    "plans.status.active": "En curso",
    "plans.status.closed": "Completado",
    "plans.status.overdue": "Vencido",
    "cycles.new": "Nuevo ciclo",
    "cycles.list": "Ciclos cargados",
    "onboarding.title": "Primeros pasos",
    "onboarding.progress": "Progreso de configuración",
  },
  en: {
    "nav.home": "Home",
    "nav.people": "People",
    "nav.evaluations": "Evaluations",
    "nav.cycles": "Cycles",
    "nav.metrics": "Objectives / KPIs",
    "nav.metricsShort": "KPIs",
    "nav.skills": "Competencies",
    "nav.development": "Development",
    "nav.report": "Reports",
    "nav.dataCenter": "Data center",
    "nav.import": "Import",
    "nav.users": "Users",
    "nav.settings": "Settings",
    "nav.platform": "Platform",
    "nav.organizations": "Organizations",
    "nav.news": "Updates",
    "topbar.organization": "Active organization",
    "topbar.searchPlaceholder": "Search… (Ctrl+K)",
    "topbar.searchHint": "Search applies to the visible lists.",
    "topbar.notifications": "Notifications",
    "topbar.news": "Updates",
    "topbar.logout": "Sign out",
    "topbar.upToDate": "Up to date",
    "common.soon": "Soon",
    "common.language": "Language",
    "common.english": "English (US)",
    "common.spanish": "Español",
    "common.searchApplies": "Search applies to the visible lists in this screen.",
    "common.retry": "Retry",
    "common.close": "Close",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.loading": "Loading...",
    "common.noData": "No data",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.status": "Status",
    "common.name": "Name",
    "common.email": "Email",
    "common.role": "Role",
    "common.area": "Department",
    "common.date": "Date",
    "common.actions": "Actions",
    "common.records": "Records",
    "common.results": "Results",
    "common.seeMore": "See more",
    "common.seeLess": "See less",
    "dashboard.greeting.morning": "Good morning",
    "dashboard.greeting.afternoon": "Good afternoon",
    "dashboard.greeting.evening": "Good evening",
    "dashboard.tour": "Guided tour",
    "dashboard.tourSub": "Recommended flow for a demo or pilot",
    "eval.new": "New evaluation",
    "eval.list": "Assigned evaluations",
    "eval.status.draft": "Draft",
    "eval.status.sent": "Submitted",
    "eval.status.reviewed": "Reviewed",
    "eval.status.closed": "Closed",
    "eval.type.self": "Self-evaluation",
    "eval.type.manager": "Manager review",
    "eval.type.final": "Final review",
    "exec.title": "Executive report",
    "exec.export": "Export PDF",
    "exec.summary": "Executive summary",
    "exec.signals": "Key indicators",
    "plans.new": "New plan",
    "plans.list": "Development plans",
    "plans.status.pending": "Pending",
    "plans.status.active": "In progress",
    "plans.status.closed": "Completed",
    "plans.status.overdue": "Overdue",
    "cycles.new": "New cycle",
    "cycles.list": "Evaluation cycles",
    "onboarding.title": "Getting started",
    "onboarding.progress": "Setup progress",
  },
};

export function resolveUiText(language, key, fallback = "") {
  return UI_TRANSLATIONS[language]?.[key] || fallback || key;
}
